poetry: upgrade typed-st source to 1.5.2
* typed-st [1.4.3], when compiled with newer clang versions (e.g. Apple Clang 13.0.1) and with --std=c99, throws an implicit declaration, which has been fixed in typed-st [1.5.2].

Stacktrace: ast3/Python/ast.c:4514:9: error: implicit declaration of function '_PyUnicode_DecodeUnicodeEscape' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            v = _PyUnicode_DecodeUnicodeEscape(s, len, NULL, &first_invalid_escape);
                ^
Signed-off-by: FraSharp <s23265@iisve.it>